let modInfo = {
	name: "The Dressy Tree",
	author: "Dressyapper",
	pointsName: "Points",
	id : "dressyapper",
	modFiles: ["DressyLayer.js", "tree.js", "components.js","achievements.js","Super.js","Hyper.js","Click.js","money.js","Layerverse.js","layerverse_layers/prestige.js", "layerverse_layers/math.js", "layerverse_layers/time.js", "layerverse_layers/space.js"],

	discordName: "",
	discordLink: "",
	initialStartPoints: new Decimal (0), // Used for hard resets and new players
	offlineLimit: 0,  // In hours
}

// Set your version in num and name
let VERSION = {
	num: "1",
	name:"No",
}

let changelog = `<h1>Changelog:</h1><br>
	<h3>v0.0</h3><br>
		- Not using this<br>`
		

let winText = `Congratulations! You have reached the end and beaten this game, but for now...`


// If you add new functions anywhere inside of a layer, and those functions have an effect when called, add them here.
// (The ones here are examples, all official functions are already taken care of)
var doNotCallTheseFunctionsEveryTick = ["blowUpEverything"]


function getStartPoints(){
    return new Decimal(modInfo.initialStartPoints)
}

// Determines if it should show points/sec
function canGenPoints(){
	return true
}

function getPointBase(){
	let gain = new Decimal(1)
	if (layers.A.effect().gte(1)) gain = gain.add(layers.A.effect())
	return gain
}

// Calculate points/sec!
function getPointGen() {
	if(!canGenPoints())
		return new Decimal(0)

	let gain = new Decimal(1)
	////////////////////////////////////////////////////////////////
	if (hasUpgrade('D', 11)) gain = gain.times(2)
	if (hasUpgrade('D', 12)) gain = gain.times(2)
	if (hasUpgrade('D', 13)) gain = gain.times(2)
	if (hasUpgrade('D', 14)) gain = gain.times(2)
	if (hasUpgrade('D', 15)) gain = gain.times(1.01)
	if (hasUpgrade('D', 16)) gain = gain.pow(1.01)
	if (hasUpgrade('D', 21)) gain = gain.times(1.01)
	if (hasUpgrade('D', 22)) gain = gain.times(1.23)
	if (hasUpgrade('D', 23)) gain = gain.times(2.31)
	if (hasUpgrade('D', 24)) gain = gain.times(3.21)		
	if (hasUpgrade('D', 25)) gain = gain.times(5)
	if (hasUpgrade('D', 26)) gain = gain.times(22)
	if (getBuyableAmount('D', '11').gte(1)) mult = mult.times(getBuyableAmount('D', '11').pow(player.D.Dbuyablepower)).add(1)
	if (hasMilestone('S', 1)) gain = gain.times(1.5)
	if (hasUpgrade('S', 11)) gain = gain.times(upgradeEffect('S', 11))	
	if (hasUpgrade('S', 12)) gain = gain.times(upgradeEffect('S', 12))
	if (hasUpgrade('S', 21)) gain = gain.times(1.1)
	if (hasUpgrade('S', 22)) gain = gain.times(2)
	if (hasUpgrade('S', 23)) gain = gain.times(3.33)
	if (hasUpgrade('S', 24)) gain = gain.times(upgradeEffect('S', 24))
	if (hasUpgrade('S', 25)) gain = gain.pow(1.05)
	if (hasUpgrade('S', 31)) gain = gain.times(6)
	if (hasUpgrade('S', 33)) gain = gain.times(upgradeEffect('S', 33))
	if (hasMilestone('H', 1)) gain = gain.pow(1.1)
	if (getBuyableAmount("M",11).gte(0)) gain = gain.times(buyableEffect("M",11))
	if (hasUpgrade('D', 34)) gain = gain.times(3)
	if (hasUpgrade('D', 35)) gain = gain.times(1.5)
	if (layers.L.effect().gte(1)) gain = gain.times(layers.L.effect())
	if (hasUpgrade('L', 16)) gain = gain.times(upgradeEffect('L', 16))	
	if (hasUpgrade('L', 12)) gain = gain.times(5)

	//LAYERVERSE
	if (hasChallenge('L',11)) gain = gain.times(challengeEffect('L', 11))
	if (hasChallenge('L',12)) gain = gain.times(challengeEffect('L', 12))
	if (hasChallenge('L',13)) gain = gain.times(challengeEffect('L', 13))

	if (hasUpgrade('P', 11)) gain = gain.times(10)
	
	if (hasUpgrade('Ma', 11)) gain = gain.add(upgradeEffect('Ma', 11))
	if (hasUpgrade('Ma', 15)) gain = gain.pow(upgradeEffect('Ma', 15))	
	if (hasUpgrade('Ma', 22)) gain = gain.times(upgradeEffect('Ma', 22))	
	if (hasUpgrade('Ma', 23)) gain = gain.times(upgradeEffect('Ma', 23))
	if (hasUpgrade('Ma', 24)) gain = gain.times(upgradeEffect('Ma', 24))
	if (hasUpgrade("Ma",31)) gain = gain.times(upgradeEffect("Ma",31))
	if (hasUpgrade("Ma",32)) gain = gain.times(upgradeEffect("Ma",32))
	if (hasUpgrade("Ma",33)) gain = gain.times(upgradeEffect("Ma",33))
	if (hasUpgrade("Ma",34)) gain = gain.times(upgradeEffect("Ma",34))   	   			
	
	if (hasUpgrade('Da', 11)) gain = gain.times(3)
	if (hasUpgrade('Da', 14)) gain = gain.times(1.5)
	if (hasUpgrade('Da', 16)) gain = gain.times(upgradeEffect("Da",16))
	if (hasUpgrade('St', 11)) gain = gain.times(upgradeEffect("St",11))
	if (hasUpgrade('St', 12)) gain = gain.times(upgradeEffect("St",12))
	if (hasUpgrade('St', 15)) gain = gain.times(5)
	if (hasUpgrade('St', 15)) gain = gain.times(2.5)
	if (hasMilestone('Hy', 2)) gain = gain.times(2)
	
	return gain
}

// You can add non-layer related variables that should to into "player" and be saved here, along with default values
function addedPlayerData() { return {
	layerview: 0,
	endgame: new Decimal("1eee1000"),
	saves: {
		time: "eyJ0YWIiOiJvcHRpb25zLXRhYiIsIm5hdlRhYiI6InRyZWUtdGFiIiwidGltZSI6MTc1MjMzMTA1MDQ3Mywibm90aWZ5Ijp7fSwidmVyc2lvblR5cGUiOiJkcmVzc3lhcHBlciIsInZlcnNpb24iOiIxIiwidGltZVBsYXllZCI6NTUuOTkwOTk5OTk5OTk5Mzc0LCJrZWVwR29pbmciOmZhbHNlLCJoYXNOYU4iOmZhbHNlLCJwb2ludHMiOiI0MS4xMDQwMDk2ODA1MjU0MiIsInN1YnRhYnMiOnsiY2hhbmdlbG9nLXRhYiI6e30sIkQiOnsibWFpblRhYnMiOiJEcmVzc3kgbGF5ZXIifSwiRGUiOnsibWFpblRhYnMiOiJBY2hpZXZlbWVudHMifSwiTWkiOnsibWFpblRhYnMiOiJDbGlja3kifSwiTCI6eyJtYWluVGFicyI6IkNoYWxsZW5nZXMifSwiTSI6eyJtYWluVGFicyI6Ik1vbmV5In19LCJsYXN0U2FmZVRhYiI6IkwiLCJsYXllcnZpZXciOjAsImVuZGdhbWUiOiIxZTEwMCIsImluZm9ib3hlcyI6e30sImluZm8tdGFiIjp7InVubG9ja2VkIjp0cnVlLCJ0b3RhbCI6IjAiLCJiZXN0IjoiMCIsInJlc2V0VGltZSI6NTUuOTkwOTk5OTk5OTk5Mzc0LCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6e30sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sIm9wdGlvbnMtdGFiIjp7InVubG9ja2VkIjp0cnVlLCJ0b3RhbCI6IjAiLCJiZXN0IjoiMCIsInJlc2V0VGltZSI6NTUuOTkwOTk5OTk5OTk5Mzc0LCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6e30sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sImNoYW5nZWxvZy10YWIiOnsidW5sb2NrZWQiOnRydWUsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjo1NS45OTA5OTk5OTk5OTkzNzQsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwiYmxhbmsiOnsidW5sb2NrZWQiOnRydWUsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjo1NS45OTA5OTk5OTk5OTkzNzQsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwidHJlZS10YWIiOnsidW5sb2NrZWQiOnRydWUsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjo1NS45OTA5OTk5OTk5OTkzNzQsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwiRCI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMCIsIkRidXlhYmxlcG93ZXIiOiIxIiwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjEwLjQ4NjAwMDAwMDAwMDAwOCwiZm9yY2VUb29sdGlwIjpmYWxzZSwiYnV5YWJsZXMiOnsiMTEiOiIwIn0sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sIkRlIjp7InVubG9ja2VkIjp0cnVlLCJwb2ludHMiOiIwIiwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjU1Ljk5MDk5OTk5OTk5OTM3NCwiZm9yY2VUb29sdGlwIjpmYWxzZSwiYnV5YWJsZXMiOnt9LCJub1Jlc3BlY0NvbmZpcm0iOmZhbHNlLCJjbGlja2FibGVzIjp7fSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsInVwZ3JhZGVzIjpbXSwibWlsZXN0b25lcyI6W10sImxhc3RNaWxlc3RvbmUiOm51bGwsImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnt9LCJncmlkIjp7fSwicHJldlRhYiI6IiJ9LCJTIjp7InVubG9ja2VkIjpmYWxzZSwicG9pbnRzIjoiMCIsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjoxMC40ODYwMDAwMDAwMDAwMDgsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7IjExIjowfSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwiSCI6eyJ1bmxvY2tlZCI6ZmFsc2UsInBvaW50cyI6IjAiLCJlZmZib29zdCI6IjEiLCJ0b3RhbCI6IjAiLCJiZXN0IjoiMCIsInJlc2V0VGltZSI6MTAuNDg2MDAwMDAwMDAwMDA4LCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6e30sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6eyIxMSI6MH0sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sIk1pIjp7InVubG9ja2VkIjp0cnVlLCJwb2ludHMiOiIwIiwiY2xpY2t5IjoiMSIsImNsaWNreW11bHQiOiIxIiwiYnV5YWJsZWJvb3N0IjoiMSIsImJ1eWFibGVib29zdDIiOiIxIiwiUGdlbiI6IjAiLCJ0b3RhbCI6IjAiLCJiZXN0IjoiMCIsInJlc2V0VGltZSI6NTUuOTkwOTk5OTk5OTk5Mzc0LCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6eyIxMSI6IjAiLCIxMiI6IjAifSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6eyIxMSI6IiJ9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sIk0iOnsidW5sb2NrZWQiOnRydWUsInBvaW50cyI6IjAiLCJtb25leWdhaW4iOiIwIiwibW9uZXltdWx0IjoiMSIsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjoxMC40ODYwMDAwMDAwMDAwMDgsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7IjExIjoiMCIsIjEyIjoiMCIsIjEzIjoiMCIsIjE0IjoiMCIsIjE1IjoiMCIsIjk5OTk5MSI6IjAifSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwiTCI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMCIsImNvbXBsZXRlIjoiMCIsImluY2hhbGxlbmdlIjpmYWxzZSwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjEwLjQ4NjAwMDAwMDAwMDAwOCwiZm9yY2VUb29sdGlwIjpmYWxzZSwiYnV5YWJsZXMiOnt9LCJub1Jlc3BlY0NvbmZpcm0iOmZhbHNlLCJjbGlja2FibGVzIjp7fSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsInVwZ3JhZGVzIjpbXSwibWlsZXN0b25lcyI6W10sImxhc3RNaWxlc3RvbmUiOm51bGwsImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnsiMTEiOjEsIjEyIjoxLCIxMyI6MH0sImdyaWQiOnt9LCJwcmV2VGFiIjoiIiwiYWN0aXZlQ2hhbGxlbmdlIjpudWxsfSwiUCI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMCIsImJ1eWFibGVwb3dlciI6IjEiLCJ0b3RhbCI6IjAiLCJiZXN0IjoiMCIsInJlc2V0VGltZSI6MTAuNDg2MDAwMDAwMDAwMDA4LCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6eyIxMSI6IjAifSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwiVCI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMTAuNDg2MDAwMDAwMDAwMDA4IiwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjEwLjQ4NjAwMDAwMDAwMDAwOCwiZm9yY2VUb29sdGlwIjpmYWxzZSwiYnV5YWJsZXMiOnt9LCJub1Jlc3BlY0NvbmZpcm0iOmZhbHNlLCJjbGlja2FibGVzIjp7fSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsInVwZ3JhZGVzIjpbXSwibWlsZXN0b25lcyI6W10sImxhc3RNaWxlc3RvbmUiOm51bGwsImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnt9LCJncmlkIjp7fSwicHJldlRhYiI6IiJ9LCJNYSI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMCIsIk1hX2VmZmVjdHBvdyI6IjEiLCJ0b3RhbCI6IjAiLCJiZXN0IjoiMCIsInJlc2V0VGltZSI6MTAuNDg2MDAwMDAwMDAwMDA4LCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6e30sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn19",
        space: "eyJ0YWIiOiJvcHRpb25zLXRhYiIsIm5hdlRhYiI6InRyZWUtdGFiIiwidGltZSI6MTc1MjkyNjIzNzExOSwibm90aWZ5Ijp7fSwidmVyc2lvblR5cGUiOiJkcmVzc3lhcHBlciIsInZlcnNpb24iOiIxIiwidGltZVBsYXllZCI6MzQwLjk0NTAwMDAwMDAwMiwia2VlcEdvaW5nIjpmYWxzZSwiaGFzTmFOIjpmYWxzZSwicG9pbnRzIjoiNzgwOC4xMTEyNzkwMzMyODIiLCJzdWJ0YWJzIjp7ImNoYW5nZWxvZy10YWIiOnt9LCJEIjp7Im1haW5UYWJzIjoiRHJlc3N5IGxheWVyIn0sIkRlIjp7Im1haW5UYWJzIjoiQWNoaWV2ZW1lbnRzIn0sIk1pIjp7Im1haW5UYWJzIjoiQ2xpY2t5In0sIkwiOnsibWFpblRhYnMiOiJDaGFsbGVuZ2VzIn0sIk0iOnsibWFpblRhYnMiOiJNb25leSJ9LCJUIjp7Im1haW5UYWJzIjoiVGltZSJ9fSwibGFzdFNhZmVUYWIiOiJMIiwibGF5ZXJ2aWV3IjowLCJlbmRnYW1lIjoiMWUxMDAiLCJzYXZlcyI6eyJ0aW1lIjoiZXlKMFlXSWlPaUp2Y0hScGIyNXpMWFJoWWlJc0ltNWhkbFJoWWlJNkluUnlaV1V0ZEdGaUlpd2lkR2x0WlNJNk1UYzFNak16TVRBMU1EUTNNeXdpYm05MGFXWjVJanA3ZlN3aWRtVnljMmx2YmxSNWNHVWlPaUprY21WemMzbGhjSEJsY2lJc0luWmxjbk5wYjI0aU9pSXhJaXdpZEdsdFpWQnNZWGxsWkNJNk5UVXVPVGt3T1RrNU9UazVPVGs1TXpjMExDSnJaV1Z3UjI5cGJtY2lPbVpoYkhObExDSm9ZWE5PWVU0aU9tWmhiSE5sTENKd2IybHVkSE1pT2lJME1TNHhNRFF3TURrMk9EQTFNalUwTWlJc0luTjFZblJoWW5NaU9uc2lZMmhoYm1kbGJHOW5MWFJoWWlJNmUzMHNJa1FpT25zaWJXRnBibFJoWW5NaU9pSkVjbVZ6YzNrZ2JHRjVaWElpZlN3aVJHVWlPbnNpYldGcGJsUmhZbk1pT2lKQlkyaHBaWFpsYldWdWRITWlmU3dpVFdraU9uc2liV0ZwYmxSaFluTWlPaUpEYkdsamEza2lmU3dpVENJNmV5SnRZV2x1VkdGaWN5STZJa05vWVd4c1pXNW5aWE1pZlN3aVRTSTZleUp0WVdsdVZHRmljeUk2SWsxdmJtVjVJbjE5TENKc1lYTjBVMkZtWlZSaFlpSTZJa3dpTENKc1lYbGxjblpwWlhjaU9qQXNJbVZ1WkdkaGJXVWlPaUl4WlRFd01DSXNJbWx1Wm05aWIzaGxjeUk2ZTMwc0ltbHVabTh0ZEdGaUlqcDdJblZ1Ykc5amEyVmtJanAwY25WbExDSjBiM1JoYkNJNklqQWlMQ0ppWlhOMElqb2lNQ0lzSW5KbGMyVjBWR2x0WlNJNk5UVXVPVGt3T1RrNU9UazVPVGs1TXpjMExDSm1iM0pqWlZSdmIyeDBhWEFpT21aaGJITmxMQ0ppZFhsaFlteGxjeUk2ZTMwc0ltNXZVbVZ6Y0dWalEyOXVabWx5YlNJNlptRnNjMlVzSW1Oc2FXTnJZV0pzWlhNaU9udDlMQ0p6Y0dWdWRFOXVRblY1WVdKc1pYTWlPaUl3SWl3aWRYQm5jbUZrWlhNaU9sdGRMQ0p0YVd4bGMzUnZibVZ6SWpwYlhTd2liR0Z6ZEUxcGJHVnpkRzl1WlNJNmJuVnNiQ3dpWVdOb2FXVjJaVzFsYm5SeklqcGJYU3dpWTJoaGJHeGxibWRsY3lJNmUzMHNJbWR5YVdRaU9udDlMQ0p3Y21WMlZHRmlJam9pSW4wc0ltOXdkR2x2Ym5NdGRHRmlJanA3SW5WdWJHOWphMlZrSWpwMGNuVmxMQ0owYjNSaGJDSTZJakFpTENKaVpYTjBJam9pTUNJc0luSmxjMlYwVkdsdFpTSTZOVFV1T1Rrd09UazVPVGs1T1RrNU16YzBMQ0ptYjNKalpWUnZiMngwYVhBaU9tWmhiSE5sTENKaWRYbGhZbXhsY3lJNmUzMHNJbTV2VW1WemNHVmpRMjl1Wm1seWJTSTZabUZzYzJVc0ltTnNhV05yWVdKc1pYTWlPbnQ5TENKemNHVnVkRTl1UW5WNVlXSnNaWE1pT2lJd0lpd2lkWEJuY21Ga1pYTWlPbHRkTENKdGFXeGxjM1J2Ym1WeklqcGJYU3dpYkdGemRFMXBiR1Z6ZEc5dVpTSTZiblZzYkN3aVlXTm9hV1YyWlcxbGJuUnpJanBiWFN3aVkyaGhiR3hsYm1kbGN5STZlMzBzSW1keWFXUWlPbnQ5TENKd2NtVjJWR0ZpSWpvaUluMHNJbU5vWVc1blpXeHZaeTEwWVdJaU9uc2lkVzVzYjJOclpXUWlPblJ5ZFdVc0luUnZkR0ZzSWpvaU1DSXNJbUpsYzNRaU9pSXdJaXdpY21WelpYUlVhVzFsSWpvMU5TNDVPVEE1T1RrNU9UazVPVGt6TnpRc0ltWnZjbU5sVkc5dmJIUnBjQ0k2Wm1Gc2MyVXNJbUoxZVdGaWJHVnpJanA3ZlN3aWJtOVNaWE53WldORGIyNW1hWEp0SWpwbVlXeHpaU3dpWTJ4cFkydGhZbXhsY3lJNmUzMHNJbk53Wlc1MFQyNUNkWGxoWW14bGN5STZJakFpTENKMWNHZHlZV1JsY3lJNlcxMHNJbTFwYkdWemRHOXVaWE1pT2x0ZExDSnNZWE4wVFdsc1pYTjBiMjVsSWpwdWRXeHNMQ0poWTJocFpYWmxiV1Z1ZEhNaU9sdGRMQ0pqYUdGc2JHVnVaMlZ6SWpwN2ZTd2laM0pwWkNJNmUzMHNJbkJ5WlhaVVlXSWlPaUlpZlN3aVlteGhibXNpT25zaWRXNXNiMk5yWldRaU9uUnlkV1VzSW5SdmRHRnNJam9pTUNJc0ltSmxjM1FpT2lJd0lpd2ljbVZ6WlhSVWFXMWxJam8xTlM0NU9UQTVPVGs1T1RrNU9Ua3pOelFzSW1admNtTmxWRzl2YkhScGNDSTZabUZzYzJVc0ltSjFlV0ZpYkdWeklqcDdmU3dpYm05U1pYTndaV05EYjI1bWFYSnRJanBtWVd4elpTd2lZMnhwWTJ0aFlteGxjeUk2ZTMwc0luTndaVzUwVDI1Q2RYbGhZbXhsY3lJNklqQWlMQ0oxY0dkeVlXUmxjeUk2VzEwc0ltMXBiR1Z6ZEc5dVpYTWlPbHRkTENKc1lYTjBUV2xzWlhOMGIyNWxJanB1ZFd4c0xDSmhZMmhwWlhabGJXVnVkSE1pT2x0ZExDSmphR0ZzYkdWdVoyVnpJanA3ZlN3aVozSnBaQ0k2ZTMwc0luQnlaWFpVWVdJaU9pSWlmU3dpZEhKbFpTMTBZV0lpT25zaWRXNXNiMk5yWldRaU9uUnlkV1VzSW5SdmRHRnNJam9pTUNJc0ltSmxjM1FpT2lJd0lpd2ljbVZ6WlhSVWFXMWxJam8xTlM0NU9UQTVPVGs1T1RrNU9Ua3pOelFzSW1admNtTmxWRzl2YkhScGNDSTZabUZzYzJVc0ltSjFlV0ZpYkdWeklqcDdmU3dpYm05U1pYTndaV05EYjI1bWFYSnRJanBtWVd4elpTd2lZMnhwWTJ0aFlteGxjeUk2ZTMwc0luTndaVzUwVDI1Q2RYbGhZbXhsY3lJNklqQWlMQ0oxY0dkeVlXUmxjeUk2VzEwc0ltMXBiR1Z6ZEc5dVpYTWlPbHRkTENKc1lYTjBUV2xzWlhOMGIyNWxJanB1ZFd4c0xDSmhZMmhwWlhabGJXVnVkSE1pT2x0ZExDSmphR0ZzYkdWdVoyVnpJanA3ZlN3aVozSnBaQ0k2ZTMwc0luQnlaWFpVWVdJaU9pSWlmU3dpUkNJNmV5SjFibXh2WTJ0bFpDSTZkSEoxWlN3aWNHOXBiblJ6SWpvaU1DSXNJa1JpZFhsaFlteGxjRzkzWlhJaU9pSXhJaXdpZEc5MFlXd2lPaUl3SWl3aVltVnpkQ0k2SWpBaUxDSnlaWE5sZEZScGJXVWlPakV3TGpRNE5qQXdNREF3TURBd01EQXdPQ3dpWm05eVkyVlViMjlzZEdsd0lqcG1ZV3h6WlN3aVluVjVZV0pzWlhNaU9uc2lNVEVpT2lJd0luMHNJbTV2VW1WemNHVmpRMjl1Wm1seWJTSTZabUZzYzJVc0ltTnNhV05yWVdKc1pYTWlPbnQ5TENKemNHVnVkRTl1UW5WNVlXSnNaWE1pT2lJd0lpd2lkWEJuY21Ga1pYTWlPbHRkTENKdGFXeGxjM1J2Ym1WeklqcGJYU3dpYkdGemRFMXBiR1Z6ZEc5dVpTSTZiblZzYkN3aVlXTm9hV1YyWlcxbGJuUnpJanBiWFN3aVkyaGhiR3hsYm1kbGN5STZlMzBzSW1keWFXUWlPbnQ5TENKd2NtVjJWR0ZpSWpvaUluMHNJa1JsSWpwN0luVnViRzlqYTJWa0lqcDBjblZsTENKd2IybHVkSE1pT2lJd0lpd2lkRzkwWVd3aU9pSXdJaXdpWW1WemRDSTZJakFpTENKeVpYTmxkRlJwYldVaU9qVTFMams1TURrNU9UazVPVGs1T1RNM05Dd2labTl5WTJWVWIyOXNkR2x3SWpwbVlXeHpaU3dpWW5WNVlXSnNaWE1pT250OUxDSnViMUpsYzNCbFkwTnZibVpwY20waU9tWmhiSE5sTENKamJHbGphMkZpYkdWeklqcDdmU3dpYzNCbGJuUlBia0oxZVdGaWJHVnpJam9pTUNJc0luVndaM0poWkdWeklqcGJYU3dpYldsc1pYTjBiMjVsY3lJNlcxMHNJbXhoYzNSTmFXeGxjM1J2Ym1VaU9tNTFiR3dzSW1GamFHbGxkbVZ0Wlc1MGN5STZXMTBzSW1Ob1lXeHNaVzVuWlhNaU9udDlMQ0puY21sa0lqcDdmU3dpY0hKbGRsUmhZaUk2SWlKOUxDSlRJanA3SW5WdWJHOWphMlZrSWpwbVlXeHpaU3dpY0c5cGJuUnpJam9pTUNJc0luUnZkR0ZzSWpvaU1DSXNJbUpsYzNRaU9pSXdJaXdpY21WelpYUlVhVzFsSWpveE1DNDBPRFl3TURBd01EQXdNREF3TURnc0ltWnZjbU5sVkc5dmJIUnBjQ0k2Wm1Gc2MyVXNJbUoxZVdGaWJHVnpJanA3ZlN3aWJtOVNaWE53WldORGIyNW1hWEp0SWpwbVlXeHpaU3dpWTJ4cFkydGhZbXhsY3lJNmUzMHNJbk53Wlc1MFQyNUNkWGxoWW14bGN5STZJakFpTENKMWNHZHlZV1JsY3lJNlcxMHNJbTFwYkdWemRHOXVaWE1pT2x0ZExDSnNZWE4wVFdsc1pYTjBiMjVsSWpwdWRXeHNMQ0poWTJocFpYWmxiV1Z1ZEhNaU9sdGRMQ0pqYUdGc2JHVnVaMlZ6SWpwN0lqRXhJam93ZlN3aVozSnBaQ0k2ZTMwc0luQnlaWFpVWVdJaU9pSWlmU3dpU0NJNmV5SjFibXh2WTJ0bFpDSTZabUZzYzJVc0luQnZhVzUwY3lJNklqQWlMQ0psWm1aaWIyOXpkQ0k2SWpFaUxDSjBiM1JoYkNJNklqQWlMQ0ppWlhOMElqb2lNQ0lzSW5KbGMyVjBWR2x0WlNJNk1UQXVORGcyTURBd01EQXdNREF3TURBNExDSm1iM0pqWlZSdmIyeDBhWEFpT21aaGJITmxMQ0ppZFhsaFlteGxjeUk2ZTMwc0ltNXZVbVZ6Y0dWalEyOXVabWx5YlNJNlptRnNjMlVzSW1Oc2FXTnJZV0pzWlhNaU9udDlMQ0p6Y0dWdWRFOXVRblY1WVdKc1pYTWlPaUl3SWl3aWRYQm5jbUZrWlhNaU9sdGRMQ0p0YVd4bGMzUnZibVZ6SWpwYlhTd2liR0Z6ZEUxcGJHVnpkRzl1WlNJNmJuVnNiQ3dpWVdOb2FXVjJaVzFsYm5SeklqcGJYU3dpWTJoaGJHeGxibWRsY3lJNmV5SXhNU0k2TUgwc0ltZHlhV1FpT250OUxDSndjbVYyVkdGaUlqb2lJbjBzSWsxcElqcDdJblZ1Ykc5amEyVmtJanAwY25WbExDSndiMmx1ZEhNaU9pSXdJaXdpWTJ4cFkydDVJam9pTVNJc0ltTnNhV05yZVcxMWJIUWlPaUl4SWl3aVluVjVZV0pzWldKdmIzTjBJam9pTVNJc0ltSjFlV0ZpYkdWaWIyOXpkRElpT2lJeElpd2lVR2RsYmlJNklqQWlMQ0owYjNSaGJDSTZJakFpTENKaVpYTjBJam9pTUNJc0luSmxjMlYwVkdsdFpTSTZOVFV1T1Rrd09UazVPVGs1T1RrNU16YzBMQ0ptYjNKalpWUnZiMngwYVhBaU9tWmhiSE5sTENKaWRYbGhZbXhsY3lJNmV5SXhNU0k2SWpBaUxDSXhNaUk2SWpBaWZTd2libTlTWlhOd1pXTkRiMjVtYVhKdElqcG1ZV3h6WlN3aVkyeHBZMnRoWW14bGN5STZleUl4TVNJNklpSjlMQ0p6Y0dWdWRFOXVRblY1WVdKc1pYTWlPaUl3SWl3aWRYQm5jbUZrWlhNaU9sdGRMQ0p0YVd4bGMzUnZibVZ6SWpwYlhTd2liR0Z6ZEUxcGJHVnpkRzl1WlNJNmJuVnNiQ3dpWVdOb2FXVjJaVzFsYm5SeklqcGJYU3dpWTJoaGJHeGxibWRsY3lJNmUzMHNJbWR5YVdRaU9udDlMQ0p3Y21WMlZHRmlJam9pSW4wc0lrMGlPbnNpZFc1c2IyTnJaV1FpT25SeWRXVXNJbkJ2YVc1MGN5STZJakFpTENKdGIyNWxlV2RoYVc0aU9pSXdJaXdpYlc5dVpYbHRkV3gwSWpvaU1TSXNJblJ2ZEdGc0lqb2lNQ0lzSW1KbGMzUWlPaUl3SWl3aWNtVnpaWFJVYVcxbElqb3hNQzQwT0RZd01EQXdNREF3TURBd01EZ3NJbVp2Y21ObFZHOXZiSFJwY0NJNlptRnNjMlVzSW1KMWVXRmliR1Z6SWpwN0lqRXhJam9pTUNJc0lqRXlJam9pTUNJc0lqRXpJam9pTUNJc0lqRTBJam9pTUNJc0lqRTFJam9pTUNJc0lqazVPVGs1TVNJNklqQWlmU3dpYm05U1pYTndaV05EYjI1bWFYSnRJanBtWVd4elpTd2lZMnhwWTJ0aFlteGxjeUk2ZTMwc0luTndaVzUwVDI1Q2RYbGhZbXhsY3lJNklqQWlMQ0oxY0dkeVlXUmxjeUk2VzEwc0ltMXBiR1Z6ZEc5dVpYTWlPbHRkTENKc1lYTjBUV2xzWlhOMGIyNWxJanB1ZFd4c0xDSmhZMmhwWlhabGJXVnVkSE1pT2x0ZExDSmphR0ZzYkdWdVoyVnpJanA3ZlN3aVozSnBaQ0k2ZTMwc0luQnlaWFpVWVdJaU9pSWlmU3dpVENJNmV5SjFibXh2WTJ0bFpDSTZkSEoxWlN3aWNHOXBiblJ6SWpvaU1DSXNJbU52YlhCc1pYUmxJam9pTUNJc0ltbHVZMmhoYkd4bGJtZGxJanBtWVd4elpTd2lkRzkwWVd3aU9pSXdJaXdpWW1WemRDSTZJakFpTENKeVpYTmxkRlJwYldVaU9qRXdMalE0TmpBd01EQXdNREF3TURBd09Dd2labTl5WTJWVWIyOXNkR2x3SWpwbVlXeHpaU3dpWW5WNVlXSnNaWE1pT250OUxDSnViMUpsYzNCbFkwTnZibVpwY20waU9tWmhiSE5sTENKamJHbGphMkZpYkdWeklqcDdmU3dpYzNCbGJuUlBia0oxZVdGaWJHVnpJam9pTUNJc0luVndaM0poWkdWeklqcGJYU3dpYldsc1pYTjBiMjVsY3lJNlcxMHNJbXhoYzNSTmFXeGxjM1J2Ym1VaU9tNTFiR3dzSW1GamFHbGxkbVZ0Wlc1MGN5STZXMTBzSW1Ob1lXeHNaVzVuWlhNaU9uc2lNVEVpT2pFc0lqRXlJam94TENJeE15STZNSDBzSW1keWFXUWlPbnQ5TENKd2NtVjJWR0ZpSWpvaUlpd2lZV04wYVhabFEyaGhiR3hsYm1kbElqcHVkV3hzZlN3aVVDSTZleUoxYm14dlkydGxaQ0k2ZEhKMVpTd2ljRzlwYm5Seklqb2lNQ0lzSW1KMWVXRmliR1Z3YjNkbGNpSTZJakVpTENKMGIzUmhiQ0k2SWpBaUxDSmlaWE4wSWpvaU1DSXNJbkpsYzJWMFZHbHRaU0k2TVRBdU5EZzJNREF3TURBd01EQXdNREE0TENKbWIzSmpaVlJ2YjJ4MGFYQWlPbVpoYkhObExDSmlkWGxoWW14bGN5STZleUl4TVNJNklqQWlmU3dpYm05U1pYTndaV05EYjI1bWFYSnRJanBtWVd4elpTd2lZMnhwWTJ0aFlteGxjeUk2ZTMwc0luTndaVzUwVDI1Q2RYbGhZbXhsY3lJNklqQWlMQ0oxY0dkeVlXUmxjeUk2VzEwc0ltMXBiR1Z6ZEc5dVpYTWlPbHRkTENKc1lYTjBUV2xzWlhOMGIyNWxJanB1ZFd4c0xDSmhZMmhwWlhabGJXVnVkSE1pT2x0ZExDSmphR0ZzYkdWdVoyVnpJanA3ZlN3aVozSnBaQ0k2ZTMwc0luQnlaWFpVWVdJaU9pSWlmU3dpVkNJNmV5SjFibXh2WTJ0bFpDSTZkSEoxWlN3aWNHOXBiblJ6SWpvaU1UQXVORGcyTURBd01EQXdNREF3TURBNElpd2lkRzkwWVd3aU9pSXdJaXdpWW1WemRDSTZJakFpTENKeVpYTmxkRlJwYldVaU9qRXdMalE0TmpBd01EQXdNREF3TURBd09Dd2labTl5WTJWVWIyOXNkR2x3SWpwbVlXeHpaU3dpWW5WNVlXSnNaWE1pT250OUxDSnViMUpsYzNCbFkwTnZibVpwY20waU9tWmhiSE5sTENKamJHbGphMkZpYkdWeklqcDdmU3dpYzNCbGJuUlBia0oxZVdGaWJHVnpJam9pTUNJc0luVndaM0poWkdWeklqcGJYU3dpYldsc1pYTjBiMjVsY3lJNlcxMHNJbXhoYzNSTmFXeGxjM1J2Ym1VaU9tNTFiR3dzSW1GamFHbGxkbVZ0Wlc1MGN5STZXMTBzSW1Ob1lXeHNaVzVuWlhNaU9udDlMQ0puY21sa0lqcDdmU3dpY0hKbGRsUmhZaUk2SWlKOUxDSk5ZU0k2ZXlKMWJteHZZMnRsWkNJNmRISjFaU3dpY0c5cGJuUnpJam9pTUNJc0lrMWhYMlZtWm1WamRIQnZkeUk2SWpFaUxDSjBiM1JoYkNJNklqQWlMQ0ppWlhOMElqb2lNQ0lzSW5KbGMyVjBWR2x0WlNJNk1UQXVORGcyTURBd01EQXdNREF3TURBNExDSm1iM0pqWlZSdmIyeDBhWEFpT21aaGJITmxMQ0ppZFhsaFlteGxjeUk2ZTMwc0ltNXZVbVZ6Y0dWalEyOXVabWx5YlNJNlptRnNjMlVzSW1Oc2FXTnJZV0pzWlhNaU9udDlMQ0p6Y0dWdWRFOXVRblY1WVdKc1pYTWlPaUl3SWl3aWRYQm5jbUZrWlhNaU9sdGRMQ0p0YVd4bGMzUnZibVZ6SWpwYlhTd2liR0Z6ZEUxcGJHVnpkRzl1WlNJNmJuVnNiQ3dpWVdOb2FXVjJaVzFsYm5SeklqcGJYU3dpWTJoaGJHeGxibWRsY3lJNmUzMHNJbWR5YVdRaU9udDlMQ0p3Y21WMlZHRmlJam9pSW4xOSJ9LCJpbmZvYm94ZXMiOnt9LCJpbmZvLXRhYiI6eyJ1bmxvY2tlZCI6dHJ1ZSwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjM0MC45NDUwMDAwMDAwMDIsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwib3B0aW9ucy10YWIiOnsidW5sb2NrZWQiOnRydWUsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjozNDAuOTQ1MDAwMDAwMDAyLCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6e30sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sImNoYW5nZWxvZy10YWIiOnsidW5sb2NrZWQiOnRydWUsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjozNDAuOTQ1MDAwMDAwMDAyLCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6e30sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sImJsYW5rIjp7InVubG9ja2VkIjp0cnVlLCJ0b3RhbCI6IjAiLCJiZXN0IjoiMCIsInJlc2V0VGltZSI6MzQwLjk0NTAwMDAwMDAwMiwiZm9yY2VUb29sdGlwIjpmYWxzZSwiYnV5YWJsZXMiOnt9LCJub1Jlc3BlY0NvbmZpcm0iOmZhbHNlLCJjbGlja2FibGVzIjp7fSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsInVwZ3JhZGVzIjpbXSwibWlsZXN0b25lcyI6W10sImxhc3RNaWxlc3RvbmUiOm51bGwsImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnt9LCJncmlkIjp7fSwicHJldlRhYiI6IiJ9LCJ0cmVlLXRhYiI6eyJ1bmxvY2tlZCI6dHJ1ZSwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjM0MC45NDUwMDAwMDAwMDIsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwiRCI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMCIsIkRidXlhYmxlcG93ZXIiOiIxIiwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjI0My41MjQ5OTk5OTk5OTkxMiwiZm9yY2VUb29sdGlwIjpmYWxzZSwiYnV5YWJsZXMiOnsiMTEiOiIwIn0sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sIkRlIjp7InVubG9ja2VkIjp0cnVlLCJwb2ludHMiOiIwIiwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjM0MC45NDUwMDAwMDAwMDIsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6eyIxMSI6IiJ9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sIlMiOnsidW5sb2NrZWQiOmZhbHNlLCJwb2ludHMiOiIwIiwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjI0My41MjQ5OTk5OTk5OTkxMiwiZm9yY2VUb29sdGlwIjpmYWxzZSwiYnV5YWJsZXMiOnt9LCJub1Jlc3BlY0NvbmZpcm0iOmZhbHNlLCJjbGlja2FibGVzIjp7fSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsInVwZ3JhZGVzIjpbXSwibWlsZXN0b25lcyI6W10sImxhc3RNaWxlc3RvbmUiOm51bGwsImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnsiMTEiOjB9LCJncmlkIjp7fSwicHJldlRhYiI6IiJ9LCJIIjp7InVubG9ja2VkIjpmYWxzZSwicG9pbnRzIjoiMCIsImVmZmJvb3N0IjoiMSIsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjoyNDMuNTI0OTk5OTk5OTk5MTIsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7IjExIjowfSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwiTCI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMCIsImNvbXBsZXRlIjoiMCIsImluY2hhbGxlbmdlIjpmYWxzZSwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjI0My41MjQ5OTk5OTk5OTkxMiwiZm9yY2VUb29sdGlwIjpmYWxzZSwiYnV5YWJsZXMiOnt9LCJub1Jlc3BlY0NvbmZpcm0iOmZhbHNlLCJjbGlja2FibGVzIjp7fSwic3BlbnRPbkJ1eWFibGVzIjoiMCIsInVwZ3JhZGVzIjpbXSwibWlsZXN0b25lcyI6W10sImxhc3RNaWxlc3RvbmUiOm51bGwsImFjaGlldmVtZW50cyI6W10sImNoYWxsZW5nZXMiOnsiMTEiOjEsIjEyIjoxLCIxMyI6MSwiMTQiOjB9LCJncmlkIjp7fSwicHJldlRhYiI6IiIsImFjdGl2ZUNoYWxsZW5nZSI6bnVsbH0sIk0iOnsidW5sb2NrZWQiOnRydWUsInBvaW50cyI6IjAiLCJtb25leWdhaW4iOiIwIiwibW9uZXltdWx0IjoiMSIsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjoyNDMuNTI0OTk5OTk5OTk5MTIsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7IjExIjoiMCIsIjEyIjoiMCIsIjEzIjoiMCIsIjE0IjoiMCIsIjE1IjoiMCIsIjk5OTk5MSI6IjAifSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwiTWkiOnsidW5sb2NrZWQiOnRydWUsInBvaW50cyI6IjAiLCJjbGlja3kiOiIxIiwiY2xpY2t5bXVsdCI6IjEiLCJidXlhYmxlYm9vc3QiOiIxIiwiYnV5YWJsZWJvb3N0MiI6IjEiLCJQZ2VuIjoiMCIsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjozNDAuOTQ1MDAwMDAwMDAyLCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6eyIxMSI6IjAiLCIxMiI6IjAifSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6eyIxMSI6IiJ9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sIlAiOnsidW5sb2NrZWQiOnRydWUsInBvaW50cyI6IjAiLCJidXlhYmxlcG93ZXIiOiIxIiwidG90YWwiOiIwIiwiYmVzdCI6IjAiLCJyZXNldFRpbWUiOjI0My41MjQ5OTk5OTk5OTkxMiwiZm9yY2VUb29sdGlwIjpmYWxzZSwiYnV5YWJsZXMiOnsiMTEiOiIwIn0sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sIk1hIjp7InVubG9ja2VkIjp0cnVlLCJwb2ludHMiOiIwIiwiTWFfZWZmZWN0cG93IjoiMSIsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjoyNDMuNTI0OTk5OTk5OTk5MTIsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifSwiVCI6eyJ1bmxvY2tlZCI6dHJ1ZSwicG9pbnRzIjoiMjczLjUyNjE4OTc0MDQzMTQ1IiwidG90YWwiOiIyNzMuNTI2MTg5NzQwNDMxNDUiLCJiZXN0IjoiMjczLjUyNjE4OTc0MDQzMTQ1IiwicmVzZXRUaW1lIjoyNDMuNTI0OTk5OTk5OTk5MTIsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIiLCJtdWx0IjoiMSIsInBvdyI6IjEifSwiRGEiOnsidW5sb2NrZWQiOnRydWUsInBvaW50cyI6IjAiLCJ0b3RhbCI6IjAiLCJiZXN0IjoiMCIsInJlc2V0VGltZSI6MjQzLjUyNDk5OTk5OTk5OTEyLCJmb3JjZVRvb2x0aXAiOmZhbHNlLCJidXlhYmxlcyI6e30sIm5vUmVzcGVjQ29uZmlybSI6ZmFsc2UsImNsaWNrYWJsZXMiOnt9LCJzcGVudE9uQnV5YWJsZXMiOiIwIiwidXBncmFkZXMiOltdLCJtaWxlc3RvbmVzIjpbXSwibGFzdE1pbGVzdG9uZSI6bnVsbCwiYWNoaWV2ZW1lbnRzIjpbXSwiY2hhbGxlbmdlcyI6e30sImdyaWQiOnt9LCJwcmV2VGFiIjoiIn0sIlN0Ijp7InVubG9ja2VkIjpmYWxzZSwicG9pbnRzIjoiMCIsInRvdGFsIjoiMCIsImJlc3QiOiIwIiwicmVzZXRUaW1lIjoyNDMuNTI0OTk5OTk5OTk5MTIsImZvcmNlVG9vbHRpcCI6ZmFsc2UsImJ1eWFibGVzIjp7fSwibm9SZXNwZWNDb25maXJtIjpmYWxzZSwiY2xpY2thYmxlcyI6e30sInNwZW50T25CdXlhYmxlcyI6IjAiLCJ1cGdyYWRlcyI6W10sIm1pbGVzdG9uZXMiOltdLCJsYXN0TWlsZXN0b25lIjpudWxsLCJhY2hpZXZlbWVudHMiOltdLCJjaGFsbGVuZ2VzIjp7fSwiZ3JpZCI6e30sInByZXZUYWIiOiIifX0=",
	}
}}

// Display extra things at the top of the page
var displayThings = ["3", "Text2"]

// Determines when the game "ends"
function isEndgame() {
	return player.points.gte(new Decimal(player.endgame))
}

function randint(min, max) {
	return Math.floor(Math.random() * (max - min) ) + min;
  }

// Less important things beyond this point!

// Style for the background, can be a function
var backgroundStyle = {

}

// You can change this if you have things that can be messed up by long tick lengths
function maxTickLength() {
	return (1) // Default is 1 hour which is just arbitrarily large
}

// Use this if you need to undo inflation from an older version. If the version is older than the version that fixed the issue,
// you can cap their current resources with this.
function fixOldSave(oldVersion){
}

setInterval(function() {addPoints("Mi",new Decimal(player.Mi.clicky.add(player.Mi.clickyadd).times(player.Mi.clickymult).times(buyableEffect("Mi",11)).floor()).times(player.Mi.Pgen).div(50))}, 20)